In [52]:
import numpy as np
np.random.seed(0)

In [53]:
#create wild-type example; e.g., 'ACGTA'
wt = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1],[1,0,0,0]])

wt.shape #wild-type OH shape=(Lx4)

(5, 4)

In [54]:
#create attribution matrix example
x = np.random.uniform(low=-1, high=1, size=wt.shape)

x

array([[ 0.09762701,  0.43037873,  0.20552675,  0.08976637],
       [-0.1526904 ,  0.29178823, -0.12482558,  0.783546  ],
       [ 0.92732552, -0.23311696,  0.58345008,  0.05778984],
       [ 0.13608912,  0.85119328, -0.85792788, -0.8257414 ],
       [-0.95956321,  0.66523969,  0.5563135 ,  0.7400243 ]])

In [55]:
r = 0.10 #probability of mutation
L = wt.shape[0] #length of sequence
wt_argmax = np.argmax(wt, axis=1) #index of each wild-type in the one-hot encoding

wt_argmax

array([0, 1, 2, 3, 0])

In [60]:
p_lc = np.ones(shape=wt.shape) #probability matrix
p_lc = p_lc*(r/3.)

for l in range(L):
    p_lc[l,wt_argmax[l]] = (1-r)
    
p_lc

array([[0.9       , 0.03333333, 0.03333333, 0.03333333],
       [0.03333333, 0.9       , 0.03333333, 0.03333333],
       [0.03333333, 0.03333333, 0.9       , 0.03333333],
       [0.03333333, 0.03333333, 0.03333333, 0.9       ],
       [0.9       , 0.03333333, 0.03333333, 0.03333333]])

In [61]:
x1 = x.copy()

for l in range(L):
    weighted_avg = np.average(x[l,:], weights=p_lc[l,:])
    for c in range(4):
        x1[l,c] -= weighted_avg
       
x1 #gauge-fixed (empirical) attribution matrix

array([[-0.01442636,  0.31832536,  0.09347338, -0.022287  ],
       [-0.43216747,  0.01231116, -0.40430265,  0.50406893],
       [ 0.37715384, -0.78328864,  0.03327839, -0.49238184],
       [ 0.87494457,  1.59004872, -0.11907244, -0.08688596],
       [-0.16134224,  1.46346066,  1.35453447,  1.53824526]])